In [1]:
import numpy as np

In [24]:
num = 31
chirp_num = 64

### Testing output with all one input for 1d and 2d FFT

In [25]:
inp_ones = np.ones((num, num), dtype=complex)
out_fft1d = np.fft.fft(inp_ones)
out_fft2d = np.fft.fft2(inp_ones)
#print(out_fft2d)

### Testing output with increasing index value for 2d FFT

In [26]:
vec2d = np.arange(num*num, dtype=complex)
vec =  vec2d.reshape([num,num])
test = np.fft.fft2(vec)
#print(test)

### Test case by performing 2D FFT using 1D FFTs

In [27]:
vec_test = np.arange(num*num, dtype=complex)
vec =  vec_test.reshape([num,num])
vec = np.fft.fft(vec)
vec_transpose = np.transpose(vec)
#vec_output = np.fft.fft(vec_transpose)
#vec_out = np.transpose(vec_output)
#print(vec)
#print(vec_transpose)
#print(vec_output)
#print(vec_out)

### Understanding 1D FFT Chirp by comparing to Python Output

In [28]:
num = 31
chirp_num = 64
#vec1d = np.ones(num, dtype=complex)
vec1d = np.arange(num, dtype=complex)
#print(vec1d)

In [29]:
W = complex(np.exp(-1j * 2 * np.pi / num))
A = 1.0
#print(W)

In [30]:
cosx = np.cos(2 * np.pi / num)
sinx = -np.sin(2 * np.pi / num)

complex(cosx, sinx)

(0.9795299412524945-0.20129852008866006j)

In [31]:
n = np.arange(num, dtype=float)
y = np.power(A, -n) * np.power(W, n ** 2 / 2.) *  vec1d
#print(y)

### Testing complex matrix multiplication used calculate y above
temp_complex = np.power(A, -n) * np.power(W, n ** 2 / 2.)
#print(temp_complex)

xreal = [((temp_complex[i].real * vec1d[i].real) - (temp_complex[i].imag * vec1d[i].imag))  for i in range(0, len(temp_complex))]
yreal = [((temp_complex[i].real * vec1d[i].imag) + (temp_complex[i].imag * vec1d[i].real)) for i in range(0, len(temp_complex))]

#for i in range(0, len(xreal)):
#  print(complex(xreal[i], yreal[i]))

In [32]:
yF = np.fft.fft(y, chirp_num)
#print(yF)

In [33]:
### testing Filter

L = chirp_num
N = num
n = np.arange(num, dtype=float)
v = np.zeros(chirp_num, dtype=complex)
#print(len(v), num)

W = complex(np.exp(-1j * 2 * np.pi / num))
for i in range(num):
    v[i] = np.power(W, -i ** 2 / 2.0)

#v[:num] = np.power(W, -n[:num] ** 2 / 2.)
for i in range(L-N+1, L):
    v[i] = W**(-((L-i)**2.0)/2.0)

#print(v)
vF = np.fft.fft(v, chirp_num)
#print(vF)

In [34]:
Gr = yF * vF
#print(Gr)

In [35]:
greal = [((yF[i].real * vF[i].real) - (yF[i].imag * vF[i].imag))  for i in range(0, len(yF))]
gimag = [((yF[i].real * vF[i].imag) + (yF[i].imag * vF[i].real)) for i in range(0, len(yF))]

#for i in range(0, len(greal)):
#  print(i, complex(greal[i], gimag[i]), Gr[i])

In [36]:
gk = np.fft.ifft(Gr)
#print(len(Gr))
#print(gk)

In [37]:
W = complex(np.exp(-1j * 2 * np.pi / num))
Xk = np.zeros(num, dtype=np.complex128)
for k in range(num):
    g_scale = W**((k**2.0)/2.0) 
    Xk[k] = g_scale * gk[k]
    
#print(Xk)

In [38]:
vec1d = np.ones(num, dtype=complex)
np.fft.fft(vec1d)

array([ 3.10000000e+01+0.j, -2.22044605e-16+0.j, -4.44089210e-16+0.j,
        0.00000000e+00+0.j,  4.44089210e-16+0.j,  4.44089210e-16+0.j,
        0.00000000e+00+0.j,  0.00000000e+00+0.j,  2.22044605e-16+0.j,
        2.22044605e-16+0.j,  2.22044605e-16+0.j,  2.22044605e-16+0.j,
        2.22044605e-16+0.j,  0.00000000e+00+0.j,  1.11022302e-16+0.j,
        1.52655666e-16+0.j,  1.52655666e-16+0.j,  1.11022302e-16+0.j,
        0.00000000e+00+0.j,  2.22044605e-16+0.j,  2.22044605e-16+0.j,
        2.22044605e-16+0.j,  2.22044605e-16+0.j,  2.22044605e-16+0.j,
        0.00000000e+00+0.j,  0.00000000e+00+0.j,  4.44089210e-16+0.j,
        4.44089210e-16+0.j,  0.00000000e+00+0.j, -4.44089210e-16+0.j,
       -2.22044605e-16+0.j])

### Testing 3D FFT

In [91]:
a = np.arange(27).reshape(3,3,3)
print(a)
a_3d = np.transpose(a, (2,1,0))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [100]:
a_fft1d = np.fft.fft(a)
#print(a_fft1d)
a_2d = np.transpose(a_fft1d, (0,2,1))
#print(a_2d)
a_fft2d = np.fft.fft(a_2d)
#print(a_fft2d)
a_2d_2 = np.transpose(a_fft2d, (0,2,1))
a_3d = np.transpose(a_2d_2, (2,1,0))
a_fft3d = np.fft.fft(a_3d)
a_final = np.transpose(a_fft3d, (2,1,0))
print(a_final)

[[[ 351.  +0.j          -13.5 +7.79422863j  -13.5 -7.79422863j]
  [ -40.5+23.3826859j     0.  +0.j            0.  +0.j        ]
  [ -40.5-23.3826859j     0.  +0.j            0.  +0.j        ]]

 [[-121.5+70.14805771j    0.  +0.j            0.  +0.j        ]
  [   0.  +0.j            0.  +0.j            0.  +0.j        ]
  [   0.  +0.j            0.  +0.j            0.  +0.j        ]]

 [[-121.5-70.14805771j    0.  +0.j            0.  +0.j        ]
  [   0.  +0.j            0.  +0.j            0.  +0.j        ]
  [   0.  +0.j            0.  +0.j            0.  +0.j        ]]]


In [101]:
np.fft.fftn(a)

array([[[ 351.  +0.j        ,  -13.5 +7.79422863j,  -13.5 -7.79422863j],
        [ -40.5+23.3826859j ,    0.  +0.j        ,    0.  +0.j        ],
        [ -40.5-23.3826859j ,    0.  +0.j        ,    0.  +0.j        ]],

       [[-121.5+70.14805771j,    0.  +0.j        ,    0.  +0.j        ],
        [   0.  +0.j        ,    0.  +0.j        ,    0.  +0.j        ],
        [   0.  +0.j        ,    0.  +0.j        ,    0.  +0.j        ]],

       [[-121.5-70.14805771j,    0.  +0.j        ,    0.  +0.j        ],
        [   0.  +0.j        ,    0.  +0.j        ,    0.  +0.j        ],
        [   0.  +0.j        ,    0.  +0.j        ,    0.  +0.j        ]]])